# Generated by Django 4.1.7 on 2023-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_zerowaste',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
